server:
  port: 8081
spring:
  application:
    name: evaluation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evaluate?serverTimezone=UTC
    username: root
    password: 4869
  redis:
    host: 192.168.10.100
    port: 6379
    password: 4869
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
mybatis-plus:
  type-aliases-package: com.evaluation.entity
logging:
  level:
    com.evaluation: debug